= Complete Roguelike Tutorial, using Rust + tcod
ifdef::env-github[:outfilesuffix: .adoc]

This is a port of the (in)famous Python+libtcod tutorial:

http://www.roguebasin.com/index.php?title=Complete_Roguelike_Tutorial,_using_python%2Blibtcod


The code is all implemented but we plan to clean it up in a few places before
splitting it into parts and writing the tutorial text.

The text is in the `doc` directory, you can look at the rendered tutorial at:

http://tomassedovic.github.io/roguelike-tutorial/

== Running the tutorial code

If you want to try running a part of the tutorial using the reference code here,
all you have to do is run this cargo command:

`cargo run --bin name-of-part`

For example, if you would like to run the reference code that is at the end of Part 1
then you run this command:

`cargo run --bin part-1b-movement`

== Thanks!

This tutorial has been put together by the following people:

* https://github.com/Raveline[A.D]
* https://github.com/Oscuro87[Emmanuel C]
* https://github.com/iszla[iszla]
* https://github.com/JCGrant[JCGrant]
* https://github.com/keisetsu[Jesse J. Bethel]
* https://github.com/aquarhead[LOU Xun]
* https://github.com/mipli[Michael A. Plikk]
* https://github.com/Nathanator[Nathan Jeffrey]
* https://github.com/smw[Stefan Wasilewski]
* https://github.com/tomassedovic[Tomas Sedovic]
* https://github.com/wcarss[Wyatt Carss]

(sorted alphabetically)
