= The object and the map
:source-highlighter: pygments
ifdef::env-github[:outfilesuffix: .adoc]

<<index#,Back to the index.>>

== Off-screen consoles

Before we continue, let's talk about _consoles_. In libtcod, console
is where we _draw stuff_. We've only used one so far -- the root
console. It is connected to the game window and anything you want to
show must eventually make its way there.

We can, however, create so-called _offscreen consoles_ and draw things
on them. Doing so will let us add transparency effects or only
render a portion of the console. It will also let us stack GUI windows
on top of the main game, render the info panel and the map
separately, etc.

From now on, we will draw to offscreen consoles and then compose them
into the root. It will occupy the whole screen for now.

Put this right after we initialise the root console:

[source,rust]
----
let mut con = Offscreen::new(SCREEN_WIDTH, SCREEN_HEIGHT);
----

Now call the `set_default_foreground` and `put_char` methods on `con`
instead of `root`.

And finally, blit the contents of the new console to the root console
to display them. The `blit` function takes a lot of parameters, but
the meaning is straightforward. We take the console we want to blit
_from_ (i.e. `con`), the coordinates where to start and the width and
height of the area we want to blit (we'll blit it all). Then the
destination (`root`), _where_ to start blitting (we'll use the
top-left corner) and finally a foreground and background transparency
(`0.0` is fully transparent, `1.0` completely opaque).

[source,rust]
----
blit(&mut con, (0, 0), (SCREEN_WIDTH, SCREEN_HEIGHT), &mut root, (0, 0), 1.0, 1.0);
----


== Generalising

Now that we have the `@` walking around, it would be a good idea to
step back and think a bit about the design. Having variables for the
player's coordinates is easy, but it can quickly get out of control
when you're defining things such as HP, bonuses, and inventory. We're
going to take the opportunity to generalize a bit.

Now, there can be such a thing as over-generalization, but we'll try
not to fall in that trap. What we're going to do is define the player
as a game `Object`. It will hold all position and display information
(character and color). The neat thing is that the player will just be
one instance of the `Object` struct -- it's general enough that you
can re-use it to define items on the floor, monsters, doors, stairs;
anything representable by a character on the screen. Here's the class,
with the initialization, and three common methods `move_by`, `draw`
and `clear`. The code for drawing and erasing is the same as the one
we used for the player earlier.

[source,rust]
----
struct Object {
    x: i32,
    y: i32,
    char: char,
    color: Color,
}

impl Object {
    pub fn new(x: i32, y: i32, char: char, color: Color) -> Self {
        Object {
            x: x,
            y: y,
            char: char,
            color: color,
        }
    }

    pub fn move_by(&mut self, dx: i32, dy: i32) {
        // move by the given amount
        self.x += dx;
        self.y += dy;
    }

    /// set the color and then draw the character that represents this object at its position
    pub fn draw(&self, con: &mut Console) {
        con.set_default_foreground(self.color);
        con.put_char(self.x, self.y, self.char, BackgroundFlag::None);
    }

    /// Erase the character that represents this object
    pub fn clear(&self, con: &mut Console) {
        con.put_char(self.x, self.y, ' ', BackgroundFlag::None);
    }
}
----

Now, before the main loop, we will create an actual player `Object`.
We will also add it to an array that will hold all objects in the
game. While we're at it, we'll add a yellow `@` that represents a
non-player character to test things out:

[source,rust]
----
let player = Object::new(SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2, '@', colors::WHITE);
let npc = Object::new(SCREEN_WIDTH / 2 - 5, SCREEN_HEIGHT / 2, '@', colors::YELLOW);
let mut objects = [player, npc];
----

Now we'll need to do a few changes to make it work. First in
`handle_keys` we'll use player's `move_by` method to change the
coordinates. This means we'll need to pass in (a mutable reference to) the
player object.

[source,rust]
----
fn handle_keys(root: &mut Root, player: &mut Object) -> bool {
    // ...
}
----

and update the way we call it:

[source,rust]
----
let player = &mut objects[0];
let exit = handle_keys(&mut root, player);
----

Next, the main loop will now clear all objects like this:

[source,rust]
----
for object in &objects {
    object.clear(&mut con)
}
----

and draw them like so:

[source,rust]
----
for object in &objects {
    object.draw(&mut con);
}
----

And that's it! We have a fully generic object system. Later we can
modify this to have all the info items, monsters and anything else
will require.


Here's link:part-2a-generalising.rs.txt[the code so far].

== The Map

Now let's build a map which will hold our dungeon! It will be a
two-dimensional array of tiles. We'll define its size on top of the
source file to be slightly smaller than the window size. This will
leave some space for a panel with stats that we'll add later.

[source,rust]
----
const MAP_WIDTH: i32 = 80;
const MAP_HEIGHT: i32 = 45;
----

Next we'll define colours for the tiles. We'll have two tiles for now:
_wall_ and _ground_. Let's define their _dark_ variants. When we add
field of view, we'll have to add a set for when they're lit.

[source,rust]
----
const COLOR_DARK_WALL: Color = Color { r: 0, g: 0, b: 100 };
const COLOR_DARK_GROUND: Color = Color { r: 50, g: 50, b: 150 };
----

Since the map is going to be built from tiles, we need to define them!
We'll start with two values: whether a tile is passable and whether it
blocks sight.

It's good to keep the values separate from the beginning as it will
let us have see-through but impassable tiles such as chasms or
passable tiles that block sight for secret passages. We'll create a
`Tile` struct:

[source,rust]
----
#[derive(Clone, Copy, Debug)]
struct Tile {
    blocked: bool,
    block_sight: bool,
}

impl Tile {
    pub fn empty() -> Self {
        Tile{blocked: false, block_sight: false}
    }

    pub fn wall() -> Self {
        Tile{blocked: true, block_sight: true}
    }
}
----

The `#[derive(...)]` bit automatically implements certain behaviours
(Rust calls them _traits_, other languages use _interfaces_) you list
there. `Debug` is to let us print the Tile's contents and `Clone` and
`Copy` will let us _copy_ the values on assignment or function call
instead of _moving_ them. So they'll behave like e.g. integers in this
respect.

We don't want the `Copy` behaviour for `Object` (we could accidentally
modify a copy instead of the original and get our changes lost for
example), but `Debug` is useful, so let's add `#[derive(Debug)]` to
our `Object` as well.

We've also added helper methods to build the two types of `Tiles`
we're going to be using the most.


And now the map! It's a two-dimensional array (`Vec`) of tiles. The
full type is `Vec<Vec<Tile>>` (a vec composed of vecs of tiles). Since
we're going to be passing it around a lot, let's define a shortcut:

[source,rust]
----
type Map = Vec<Vec<Tile>>;
----

This let's use write `Map` wherever we'd have to write
`Vec<Vec<Tile>>` and it's also easier to understand.


Now we'll build it using nested `vec!` macros:

[source,rust]
----
fn make_map() -> Map {
    // fill map with "unblocked" tiles
    let mut map = vec![vec![Tile::empty(); MAP_HEIGHT as usize]; MAP_WIDTH as usize];

    map
}
----

The `vec!` macro is a shortcut that creates a `Vec` and fills it with
values. For example, `vec!['a'; 42]` would create a Vec containing the
letter *'a'* 42 times. We do the same trick above to build a column of
tiles and then build the map of those columns.

We can access any tile with `map[x][y]`. Let's add two pillars
(blocked tiles) to demonstrate that and provide a simple test:

[source,rust]
----
map[30][22] = Tile::wall();
map[50][22] = Tile::wall();
----

(you can also access the tile's properties directly like so:
`map[30][22].blocked = true`)


Next we need to draw the map on our window. Since we need to
draw both the objects and the map, let's create a new function that
renders everything and call it from the main loop.

[source,rust]
----
fn render_all(root: &mut Root, con: &mut Offscreen, objects: &[Object], map: &Map) {
    // draw all objects in the list
    for object in objects {
        object.draw(con);
    }
}
----

Still in the same function, we can go through all the tiles and draw
them to the screen:

[source,rust]
----
for y in 0..MAP_HEIGHT {
    for x in 0..MAP_WIDTH {
        let wall = map[x as usize][y as usize].block_sight;
        if wall {
            con.set_char_background(x, y, COLOR_DARK_WALL, BackgroundFlag::Set);
        } else {
            con.set_char_background(x, y, COLOR_DARK_GROUND, BackgroundFlag::Set);
        }
    }
}
----

Also, move the `blit` call at the end of `render_all` since
it's part of the rendering code.

Make sure to create the map before the rendering code:

[source,rust]
----
let map = make_map();
----

You should be able to see two pillars and walk around the map now!

But wait, there's something wrong. The pillars show up, but the player
can walk over them. That's easy to fix though, add this check to the
beginning of the Object's `move_by` method:

[source,rust]
----
if !map[(self.x + dx) as usize][(self.y + dy) as usize].blocked {
    // the move code
}
----

We'll have to pass a reference to the map to `move_by` and
`handle_keys` which calls it. This may look annoying now but as the
code grows, it will be good to know which functions can see (and
change!) what.

Finally, since the `con` console is for objects and the map only, we
update its size to that of the map:

[source]
----
let mut con = Offscreen::new(MAP_WIDTH, MAP_HEIGHT);
----

And update the `blit` call, too:

[source]
----
blit(con, (0, 0), (MAP_WIDTH, MAP_HEIGHT), root, (0, 0), 1.0, 1.0);
----

Now we have some space at the bottom for the message log, status bar, etc.

Here's link:part-2b-map.rs.txt[the complete code so far].

NOTE: There's a ton of different ways to create the map. One common
alternative is one continuous Vec with `MAP_HEIGHT * MAP_WIDTH` items.
To access a tile on `(x, y)`, you would do `map[y * MAP_WIDTH + x]`.
The advantage is that you only do one array lookup instead of two and
iterating over every object in the map is faster because they're all
in the same region of memory.

NOTE: Or you could treat walls and everything else in the map as just
another `Object` and store them there. This would make the game
structure simpler (*everything* is an `Object`) and more flexible
(just add HP to make a wall destructible, or damage to one that's
supposed to be covered with spikes).

Continue to <<part-3-dungeon#,the next part>>.
