= Going Berserk!
:icons: font
:source-highlighter: pygments
:source-language: rust
ifdef::env-github[:outfilesuffix: .adoc]

<<index#,Back to the index.>>

== The Components

TODO: talk about composition vs. inhericance and how this isn't a real ECS whatever that means...

Our components will be plain `structs` with related bits of data and
not much else. Each `Object` will have some (or all or none) of the
components attached and that will drive their behaviour. Only things
with the `Fighter` component will be able to attack or be attacked,
etc..

Let's create the `Fighter` component. It will have hit points, maximum
hit points (for healing), defense and attack power.

[source]
----
// combat-related properties and methods (monster, player, NPC).
#[derive(Clone, Copy, Debug, PartialEq)]
struct Fighter {
    max_hp: i32,
    hp: i32,
    defense: i32,
    power: i32,
}
----

Next is the component for monster artificial intelligence. For now, it
will not carry any data, but we'll soon remedy that.

[source]
----
#[derive(Clone, Copy, Debug, PartialEq)]
struct Ai;
----

And update the `Object` definition:

[source]
----
fighter: Option<Fighter>,
ai: Option<Ai>,
----

and `Object::new`:

[source]
----
fighter: None,
ai: None,
----

This means that the newly-created objects will not have any
components. We can add them ourselves, though!

First the player:

[source]
----
player.fighter = Some(Fighter{max_hp: 30, hp: 30, defense: 2, power: 5});
----

(you'll need to make the `player` variable mutable because we're
changing it now)


And next the monsters. Each monster will get a `Fighter` component as
well as the `Ai` one. In `place_objcets` where the monsters are
defined:

[source]
----
if ... {
    // create an orc
    let mut orc = Object::new(x, y, 'o', "orc", colors::DESATURATED_GREEN, true);
    orc.fighter = Some(Fighter{max_hp: 10, hp: 10, defense: 0, power: 3});
    orc.ai = Some(Ai);
    orc
} else {
    // create a troll
    let mut troll = Object::new(x, y, 'T', "troll", colors::DARKER_GREEN, true);
    troll.fighter = Some(Fighter{max_hp: 16, hp: 16, defense: 1, power: 4});
    troll.ai = Some(Ai);
    troll
}
----

== AI

We went through all this trouble and yet nothing happens? Let's that
by actually using our newly-minted components! The monsters have been
growling for too long and are ready to fight now.

We'll start by creating a function that will cause an object (monster,
usually) move towards a position (the player's coordinates, usually).

[source]
----
fn move_towards(id: usize, target_x: i32, target_y: i32, map: &Map, objects: &mut [Object]) {
    // vector from this object to the target, and distance
    let dx = target_x - objects[id].x;
    let dy = target_y - objects[id].y;
    let distance = ((dx.pow(2) + dy.pow(2)) as f32).sqrt();

    // normalize it to length 1 (preserving direction), then round it and
    // convert to integer so the movement is restricted to the map grid
    let dx = (dx as f32 / distance).round() as i32;
    let dy = (dy as f32 / distance).round() as i32;
    move_by(id, dx, dy, map, objects);
}
----

Next we'll add a method on `Object` that will tell us the distance to
another object.

[source]
----
/// return the distance to another object
pub fn distance_to(&self, other: &Object) -> f32 {
    let dx = other.x - self.x;
    let dy = other.y - self.y;
    ((dx.pow(2) + dy.pow(2)) as f32).sqrt()
}
----

All right, let's use them to implement some basic behaviour: if the
monster is close, it will attack, otherwise it will move closer.

[source]
----
fn ai_take_turn(monster_id: usize, map: &Map, objects: &mut [Object], fov_map: &FovMap) {
    // a basic monster takes its turn. If you can see it, it can see you
    let (monster_x, monster_y) = objects[monster_id].pos();
    if fov_map.is_in_fov(monster_x, monster_y) {
        if objects[monster_id].distance_to(&objects[PLAYER]) >= 2.0 {
            // move towards player if far away
            let (player_x, player_y) = objects[PLAYER].pos();
            move_towards(monster_id, player_x, player_y, map, objects);
        } else if objects[PLAYER].fighter.map_or(false, |f| f.hp > 0) {
            // close enough, attack! (if the player is still alive.)
            let monster = &objects[monster_id];
            println!("The attack of the {} bounces off your shiny metal armor!", monster.name);
        }
    }
}
----

But for any of this to have effect, we need to call it from the main
loop:

[source]
----
for id in 0..objects.len() {
    if objects[id].ai.is_some() {
        ai_take_turn(id, &map, &mut objects, &fov_map);
    }
}
----

When you test it now, you can see the monsters following you around
and trying to attack you.

The whole code is available link:part-6a-ai.rs[here].

== Sword-fighting

The quest for some epic medieval combat is coming to an end! We will
now write the actual functions to attack and take damage, and replace
those silly placeholders with the meaty stuff. The "meaty stuff" is
deliberately simple. This is so you can easily change it with your own
damage system, whatever it may be.

[source]
----
pub fn take_damage(&mut self, damage: i32) {
    // apply damage if possible
    if let Some(fighter) = self.fighter.as_mut() {
        if damage > 0 {
            fighter.hp -= damage;
        }
    }
}
----

In the next section we'll modify it to also handle deaths. Then
there's the method to attack another object:

[source]
----
pub fn attack(&mut self, target: &mut Object) {
    // a simple formula for attack damage
    let damage = self.fighter.map_or(0, |f| f.power) - target.fighter.map_or(0, |f| f.defense);
    if damage > 0 {
        // make the target take some damage
        println!("{} attacks {} for {} hit points.", self.name, target.name, damage);
        target.take_damage(damage);
    } else {
        println!("{} attacks {} but it has no effect!", self.name, target.name);
    }
}
----

It calls the previous method in order to handle taking damage. We
separated "attacks" and "damage" because you might want an event, like
poison or a trap, to directly damage an object by some amount, without
going through the attack damage formula.

Let's replace the dummy attack message in `ai_take_turn` with a call
to the `attack` monster.

Alas, the ownership rears its head again! If you just tried the
straightforward bit:

[source]
----
let monster = &mut objects[monster_id];
monster.attack(&mut objects[PLAYER]);
----

You would get another error about a double mutable borrow. While
taking two mutable pointers into the `objects` list is safe when
they're pointing at *different objects*, it would be a problem if they
borrowed the same one (remember, you can only have one mutable borrow
to an object at a time).

Unfortunately, Rust can't just figure out that the monster and player
are different items in the list.

However, we can let it know! There's a method on slices called
`split_at_mut` which takes an index and returns two mutable slices
split by the index. And we can use that to return a mutable borrow to
our object from both:

[source]
----
/// Mutably borrow two *separate* elements from the given slice.
/// Panics when the indexes are equal or out of bounds.
fn mut_two<T>(first_index: usize, second_index: usize, items: &mut [T]) -> (&mut T, &mut T) {
    assert!(first_index != second_index);
    let split_at_index = cmp::max(first_index, second_index);
    let (first_slice, second_slice) = items.split_at_mut(split_at_index);
    if first_index < second_index {
        (&mut first_slice[first_index], &mut second_slice[0])
    } else {
        (&mut second_slice[0], &mut first_slice[second_index])
    }
}
----

And now monster's attack looks like this:

[source]
----
// close enough, attack! (if the player is still alive.)
let (monster, player) = mut_two(monster_id, PLAYER, objects);
monster.attack(player);
----

And do the same to the player's dummy attack code in `player_move_or_attack`:

[source]
----
let (player, target) = mut_two(PLAYER, target_id, objects);
player.attack(target);
----


That's it, the player and the monsters can beat each other silly, but
no-one will die. We'll take this opportunity to print the player's HP
so you can see it plummeting to negative values as the monsters
attack you. This is how you make a simple GUI! At the end of the
`render_all` function:

[source]
----

----


== Untimely deaths



Here's link:part-6b-untimely-deaths.rs[the complete code so far].


Continue to <<part-7-gui#,the next part>>.
