= Spells and ranged combat
:icons: font
:source-highlighter: pygments
:source-language: rust
ifdef::env-github[:outfilesuffix: .adoc]

<<index#,Back to the index.>>


The inventory we implemented has lots of untapped potential; I
encourage you to explore it fully and create as many different items
as possible! (Though the special category of items that can be
equipped, like swords and armor, will be done in a later section.) To
get the ball rolling, we'll start with some magic scrolls the player
can use to cast spells. We'll sample a few different spell types; I'm
sure you can then create tons of variants from these little examples.

== Compression Interlude

Before we begin, however, we'll do something that will make our lives
a little easier: we pull all the libtcod bits (the root, con and panel
consoles, the field-of-view map and the mouse position) into a single
struct that we can pass around at once.

As you've noticed before, some of our function arguments are getting a
bit tedious as we pass in 9 different things and the same would be
true for our item cast functions. One spell will want to select a
monster in the FOV, another needs mouse targeting, etc.

So let's put it all into a `Tcod` struct we can pass around:

[source]
----
struct Tcod {
    root: Root,
    con: Offscreen,
    panel: Offscreen,
    fov: FovMap,
    mouse: Mouse,
}
----

Next, we'll initialise it in our `main` function. Right after the
`set_fps` call, replace:

[source]
----
let mut con = Offscreen::new(MAP_WIDTH, MAP_HEIGHT);
let mut panel = Offscreen::new(SCREEN_WIDTH, PANEL_HEIGHT);
----

With:

[source]
----
let mut tcod = Tcod {
    root: root,
    con: Offscreen::new(MAP_WIDTH, MAP_HEIGHT),
    panel: Offscreen::new(SCREEN_WIDTH, PANEL_HEIGHT),
    fov: FovMap::new(MAP_WIDTH, MAP_HEIGHT),
    mouse: Default::default(),
};
----

(and remove the `fov_map` and `mouse` initialisation code, too since
it's in here)

And next, let the compiler guide us.

We have to replace a bunch of stuff in the main function: `mouse` with
`tcod.mouse`, `root` with `tcod.root`, `fov_map` with `tcod.fov`, etc.

That gets us to a compiling state, but it doesn't seem like much of a
win yet. Let's make proper use of it, then!

First, calling `render_all` from `main` can now be just:

[source]
----
render_all(&mut tcod, &objects, &mut map, &messages, fov_recompute);
----

The new `render_all` function header is:

[source]
----
fn render_all(tcod: &mut Tcod, objects: &[Object], map: &mut Map,
              messages: &Messages, fov_recompute: bool) {
    // ...
}
----

And we do the same set of transformations inside.

Next, we'll do the same to `handle_keys`. That one only takes `root`
now, but it calls the `use_item` and we'll want to pass the whole
shebang there, soon.

Main loop:

[source]
----
let player_action = handle_keys(key, &mut tcod, &map, &mut objects,
                                &mut inventory, &mut messages);
----

Function definition:

[source]
----
fn handle_keys(key: Key, tcod: &mut Tcod, map: &Map, objects: &mut Vec<Object>,
               inventory: &mut Vec<Object>, messages: &mut Messages) -> PlayerAction {
    // ...
}
----

And finally, pass `&mut Tcod` to `use_item` and `cast_heal` even
though it's of little use there yet.

Make sure that it compiles and we can move on adding more spells!

TIP: There's much more we can do here, such as moving the `menu`,
`inventory_menu`, `render_bar`, etc. as methods of `Tcod` or passing
`Tcod` everywhere we've been passing *any* of it's members now. That
largely depends on your style and how tightly you want things to be
coupled. In general, there's a ton of code that just need one or two
bits of `Tcod` but some code that basically wants all of it. The good
thing is that this struct lets us support both cases and anything in
between.

NOTE: Later on, we'll do a similar packing of the game-related stuff
such as the message log, the level map, the inventory, etc. But this
has been enough refactoring for one section!


== Magic scrolls: the Lightning Bolt

The first spell is a lightning bolt that damages the nearest enemy.
It's simple to code because it doesn't involve any targeting. On the
other hand, it creates some interesting tactical challenges: if the
nearest enemy is not the one you want to hit (for example, it's too
weak to waste the spell on it), you have to maneuver into a good
position. Just modify the `place_objects` function to choose at random
between a healing potion and a lightning bolt scroll, the same way
it's done with monsters:

[source]
----
if !is_blocked(x, y, map, objects) {
    let dice = rand::random::<f32>();
    let item = if dice < 0.7 {
        // create a healing potion (70% chance)
        let mut object = Object::new(x, y, '!', "healing potion", colors::VIOLET, false);
        object.item = Some(Item::Heal);
        object
    } else {
        // create a lightning bolt scroll (30% chance)
        let mut object = Object::new(x, y, '#', "scroll of lightning bolt",
                                     colors::LIGHT_YELLOW, false);
        object.item = Some(Item::Lightning);
        object
    };
    objects.push(item);
}
----

This means we have to add a new variant to the `Item` enum:
`Lightning`. And we need to add a new `on_use` variant to the
`use_item` (the compiler will complain if we don't). So let's do that:

[source]
----
let on_use = match item {
    Heal => cast_heal,
    Lightning => cast_lightning,
};
----

Now we need to write the `cast_lightning` function!

[source]
----
fn cast_lightning(_inventory_id: usize, objects: &mut [Object], messages: &mut Messages, tcod: &mut Tcod)
                  -> UseResult
{
    // find closest enemy (inside a maximum range and damage it)
    let monster_id = closest_monster(LIGHTNING_RANGE, objects, tcod);
    if let Some(monster_id) = monster_id {
        // zap it!
        message(messages,
                format!("A lightning bolt strikes the {} with a loud thunder! \
                         The damage is {} hit points.",
                        objects[monster_id].name, LIGHTNING_DAMAGE),
                colors::LIGHT_BLUE);
        objects[monster_id].take_damage(LIGHTNING_DAMAGE, messages);
        UseResult::UsedUp
    } else {  // no enemy found within maximum range
        message(messages, "No enemy is close enough to strike.", colors::RED);
        UseResult::Cancelled
    }
}
----

It's a plain spell but an imaginative message can always give it some
flavor! It returns uses the `UseResult::Cancelled` if cancelled to prevent the item
from being destroyed in that case, like the healing potion. There are
also a couple of new constants that have to be defined:
`LIGHTNING_DAMAGE = 20` and `LIGHTNING_RANGE = 5`.

Now we'd write the `closest_monster` method, but as soon as we start,
we'll see Rust being unhappy about our `let on_use = match item` line
in our `use_item` function.

You'll see it if you add a dummy `closest_monster` implementation and
try to compile:

[source]
----
fn closest_monster(max_range: i32, objects: &mut [Object], tcod: &Tcod) -> Option<usize> {
    unimplemented!()
}
----

Here's the error Rust reports:

----
   Compiling roguelike-tutorial v0.1.0 (file:///home/thomas/code/roguelike-tutorial)
src/bin/part-9-spells.rs:328:22: 331:10 error: match arms have incompatible types:
 expected `fn(usize, &mut [Object], &mut collections::vec::Vec<(collections::string::String, tcod::colors::Color)>, &mut Tcod) -> UseResult {cast_heal}`,
    found `fn(usize, &mut [Object], &mut collections::vec::Vec<(collections::string::String, tcod::colors::Color)>, &mut Tcod) -> UseResult {cast_lightning}`
(expected fn item,
    found a different fn item) [E0308]
src/bin/part-9-spells.rs:328         let on_use = match item {
src/bin/part-9-spells.rs:329             Heal => cast_heal,
src/bin/part-9-spells.rs:330             Lightning => cast_lightning,
src/bin/part-9-spells.rs:331         };
src/bin/part-9-spells.rs:328:22: 331:10 help: run `rustc --explain E0308` to see a detailed explanation
src/bin/part-9-spells.rs:330:26: 330:40 note: match arm with an incompatible type
src/bin/part-9-spells.rs:330             Lightning => cast_lightning,
                                                      ^~~~~~~~~~~~~~
src/bin/part-9-spells.rs:332:15: 332:21 error: the type of this value must be known in this context
src/bin/part-9-spells.rs:332         match on_use(inventory_id, objects, messages, tcod) {
                                           ^~~~~~
----

Now this may seem scary, but Rust's errors are generally quite good in
telling you what's wrong and sometimes even how to fix it.

In this case, we're apparently passing two different types to the
`match` expression. Just like `if/else`, all branches of `match` must
return the same type. Now in both cases we're returning a function
with the same signature (arguments and a return value), but the two
functions (`cast_heal` and `cast_lightning`) are actually different
and Rust treats them as separate types.

The fix here is a bit annoying but simple. We just tell rust the
signature we expect and Rust will happily figure out that both our
functions satisfy it:

[source]
----
let on_use: fn(usize, &mut [Object], &mut Messages, &mut Tcod) -> UseResult = match item {
    Heal => cast_heal,
    Lightning => cast_lightning,
};
----

And now we compile!

So let's write that `closest_monster` properly:

[source]
----
/// find closest enemy, up to a maximum range, and in the player's FOV
fn closest_monster(max_range: i32, objects: &mut [Object], tcod: &Tcod) -> Option<usize> {
    let mut closest_enemy = None;
    let mut closest_dist = (max_range + 1) as f32;  // start with (slightly more than) maximum range

    for (id, object) in objects.iter().enumerate() {
        if (id != PLAYER) && object.fighter.is_some() && object.ai.is_some() &&
            tcod.fov.is_in_fov(object.x, object.y)
        {
            // calculate distance between this object and the player
            let dist = objects[PLAYER].distance_to(object);
            if dist < closest_dist {  // it's closer, so remember it
                closest_enemy = Some(id);
                closest_dist = dist;
            }
        }
    }
    closest_enemy
}
----

We just need to loop through all the monsters, and keep track of the
closest one so far (and its distance). By initializing that distance
at a bit more than the maximum range, any monster farther away is
rejected. We also check that it's in FOV, so the player can't cast a
spell through walls.

This makes use of the `distance_to` method we wrote earlier for
the AI. Alright, the lightning bolt is done! If you have one you can
take down a Troll with a single hit, sparing you from a lot of damage.

== Spells that manipulate monsters: Confusion

There are many direct damage variants of the Lightning Bolt spell. So
we'll move on to a different sort of spell: one that affects the
monsters' actions. This can be done by replacing their AI with a
different one, that makes it do something different -- run away in
fear, stay knocked out for a few turns, even fight on the player's
side for a while!

My choice was a Confusion spell, that makes the monster move around
randomly, and not attack the player. To do this, we'll change our
empty `Ai` struct into an enum with two variants:

[source]
----
enum Ai {
    Basic,
    Confused{previous_ai: Box<Ai>, num_turns: i32},
}
----

The `Basic` option is the AI we've used until now -- a monster moves
towards a player and tries to attack.

The `Confused` one is what we want to implement now: it moves randomly
for a few turns and then reverts back to the AI it had before it got
confused.

This is still an enum, but it uses a struct-like enum variant for
`Confused`. In Rust, enums variants aren't just empty identifiers, but
can hold data, too!

We need to change the monster creation in `place_objects` a little:

[source]
----
// create an orc
orc.ai = Some(Ai::Basic);
// ...
// create a troll
troll.ai = Some(Ai::Basic);
----

Next, let's move the code from `ai_take_turn` its own function:

[source]
----
fn ai_take_turn(monster_id: usize, map: &Map, objects: &mut [Object],
                fov_map: &FovMap, messages: &mut Messages) {
    use Ai::*;
    if let Some(ai) = objects[monster_id].ai.take() {
        let new_ai = match ai {
            Basic => ai_basic(monster_id, map, objects, fov_map, messages),
            Confused{previous_ai, num_turns} => ai_confused(
                monster_id, map, objects, messages, previous_ai, num_turns)
        };
        objects[monster_id].ai = Some(new_ai);
    }
}

fn ai_basic(monster_id: usize, map: &Map, objects: &mut [Object],
            fov_map: &FovMap, messages: &mut Messages) -> Ai {
    // a basic monster takes its turn. If you can see it, it can see you
    let (monster_x, monster_y) = objects[monster_id].pos();
    if fov_map.is_in_fov(monster_x, monster_y) {
        if objects[monster_id].distance_to(&objects[PLAYER]) >= 2.0 {
            // move towards player if far away
            let (player_x, player_y) = objects[PLAYER].pos();
            move_towards(monster_id, player_x, player_y, map, objects);
        } else if objects[PLAYER].fighter.map_or(false, |f| f.hp > 0) {
            // close enough, attack! (if the player is still alive.)
            let (monster, player) = mut_two(monster_id, PLAYER, objects);
            monster.attack(player, messages);
        }
    }
    Ai::Basic
}
----

The function now does a dispatch similar to the one in `use_item`.
Based on the AI type, it calls `ai_basic` or `ai_confused`.

The `ai_basic` function now contains what was previously in
`ai_take_turn` except that now it also returns an `Ai` value. This is
because the `Ai` now can't be `Copy` (and *that's* because the
`Confused` variant uses `Box<Ai>` and boxes cannot be copied).

In the case of the `Basic` ai, we don't really care since we're not
modifying any data.

But in case of Confused, we'll want to decrease the number of
remaining turns and when they run out, swap the previous AI.

A simple way to do that without running into any ownership issues is
to take the present `Ai` value (by calling `ai.take()` -- it moves it
out, leaving `None` in its place), calling the appropriate function
(`ai_basic` or `ai_confuse`) with all its contents (i.e. `previous_ai`
and `num_turns` for `Confused`) and then put whatever `Ai` the
function returned back as the monster's `ai` component.

It's a bit complex if you haven't internalised the `Option` and `Box`
types and how the ownership works, but it's actually quite
straightforward once you do.

You can try to write `ai_take_turn` yourself without moving anything
-- just use `objects[monster_id].ai.as_mut()` to get a mutable
reference and think through the compile errors Rust will give you.

So after that mouthful, the rather anti-climactic implementation of
`ai_confused`:

[source]
----
fn ai_confused(monster_id: usize, map: &Map, objects: &mut [Object], messages: &mut Messages,
               previous_ai: Box<Ai>, num_turns: i32) -> Ai {
    if num_turns >= 0 {  // still confused ...
        // move in a random idrection, and decrease the number of turns confused
        move_by(monster_id,
                rand::thread_rng().gen_range(-1, 2),
                rand::thread_rng().gen_range(-1, 2),
                map,
                objects);
        Ai::Confused{previous_ai: previous_ai, num_turns: num_turns - 1}
    } else {  // restore the previous AI (this one will be deleted)
        message(messages, format!("The {} is no longer confused!",
                                  objects[monster_id].name),
                colors::RED);
        *previous_ai
    }
}
----

It takes pretty much the same parameters as `ai_basic`, but it moves
the monster at random if it's still confused and it returns the
previous AI otherwise.

If you look at the return values, in the confused case, we're
reconstructing the `Ai::Confused` value again, with the same
`previous_ai` and a `num_turns` decreased by one. This is where we
move `previous_ai` instead of mutating anything.

And in the `else` case, we just return `previous_ai` on its own,
getting rid of the `Confused` value entirely. We have to prepend it
with an asterisk to return the boxed value -- `Ai`. If we didn't put
the asterisk there, we'd return `Box<Ai>`, which is not what
`ai_take_turn` expects.

Now, the actual scroll that uses this AI! For it to appear in the
dungeon it must be added to `place_objects`. Notice that the chance of
getting a lightning bolt scroll must change:

[source]
----
} else if dice < 0.7 + 0.15 {
    // create a lightning bolt scroll (15% chance)
    let mut object = Object::new(x, y, '#', "scroll of lightning bolt",
                                 colors::LIGHT_YELLOW, false);
    object.item = Some(Item::Lightning);
    object
} else {
    // create a confuse scroll (15% chance)
    let mut object = Object::new(x, y, '#', "scroll of confusion",
                                 colors::LIGHT_YELLOW, false);
    object.item = Some(Item::Confuse);
    object
};
----

We're making all scrolls look the same here, but in your game that's up
to you. The `cast_confuse` function can now be defined. It hits the
closest monster for now, like the lightning bolt; later we'll allow
targeting.

[source]
----
fn cast_confuse(_inventory_id: usize, objects: &mut [Object], messages: &mut Messages, tcod: &mut Tcod)
                -> UseResult
{
    // find closest enemy in-range and confuse it
    let monster_id = closest_monster(CONFUSE_RANGE, objects, tcod);
    if let Some(monster_id) = monster_id {
        let old_ai = objects[monster_id].ai.take().unwrap_or(Ai::Basic);
        // replace the monster's AI with a "confused" one; after
        // some turns it will restore the old AI
        objects[monster_id].ai = Some(Ai::Confused {
            previous_ai: Box::new(old_ai),
            num_turns: CONFUSE_NUM_TURNS,
        });
        message(messages,
                format!("The eyes of {} look vacant, as he starts to stumble around!",
                        objects[monster_id].name),
                colors::LIGHT_GREEN);
        UseResult::UsedUp
    } else {  // no enemy fonud within maximum range
        message(messages, "No enemy is close enough to strike.", colors::RED);
        UseResult::Cancelled
    }
}
----

We find the closest enemy again, extract its existing AI and replace
it with the `Confused` one.

:unwrap: http://doc.rust-lang.org/stable/std/option/enum.Option.html#method.unwrap
:expect: http://doc.rust-lang.org/stable/std/option/enum.Option.html#method.expect
:unwrap_or: http://doc.rust-lang.org/stable/std/option/enum.Option.html#method.unwrap_or

`target_monster` should always return a monster that has the `Ai`
component, but the `Object.ai` still contains `Option<Ai>` rather than
bare `Ai` (not every Object has AI even though we expect each monster
to have one). We could use {unwrap}[the unwrap] or {expect}[expect]
methods to get the inner value, but this would crash the program
(`expect` would print a custom message). Here we use
{unwrap_or}[unwrap_or] instead which will return the `Basic` AI in
case there is none.

You may choose to panic with unwrap/expect instead (to find the bug
early and hunt it down) or log the error and keep going or even allow
monsters without AI and just handle that case properly!

We've also introduced two new constants: `CONFUSE_RANGE = 8` and
`CONFUSE_NUM_TURNS = 10`.


Finally, to tie it all together, we need to add a new item type:
`Confuse`:

[source]
----
enum Item {
    Heal,
    Lightning,
    Confuse,
}
----

And associate it with `cast_confuse` in the `use_item` function:

[source]
----
let on_use: fn(usize, &mut [Object], &mut Messages, &mut Tcod) -> UseResult = match item {
    Heal => cast_heal,
    Lightning => cast_lightning,
    Confuse => cast_confuse,
};
----



== Targeting: the Fireball

== Targeting single monsters

== Dropping items




Here's link:part-9-spells.rs[the complete code so far].

Continue to <<part-10-menu-saving#,the next part>>.
